db:
  image: mysql:5.7
  restart: always
  ports:
    - 3306:3306
  volumes:
    - db_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: secret

wordpress:
  links:
    - db:mysql
  image: wordpress:3.9.1
  restart: always
  volumes:
    # - ./wp-content:/var/www/html/wp-content
    - ./:/var/www/html/wp-content/plugins/co2ok-plugin-woocommerce/
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_PASSWORD: secret
  ports:
    - 8080:80
    - 443:443